db:
  host: localhost
  port: 5432
  user: postgres
  password: superuser
  name: user_db
  ssl_mode: disable

grpc:
  host: 0.0.0.0
  port: 50052

http:
  host: localhost
  port: 8080

cors:
  allow_origins:
    - "http://localhost:3000"  # Frontend в разработке
    - "http://127.0.0.1:3000"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Authorization"
    - "Content-Type"
    - 
services:
  auth_service:
    host: localhost
    port: 50051