db:
  host: db
  port: 5432
  user: postgres
  password: superuser
  name: user_db
  ssl_mode: disable

grpc:
  port: 50052

http:
  port: 8080

services:
  auth_service:
    host: localhost
    port: 50051