auth_service:
  db:
    host: localhost
    port: 5432
    user: auth_user
    password: auth_password
    name: auth_db
    ssl_mode: disable
  jwt:
    secret_key: super_secret_key
    access_token_duration: 15m
    refresh_token_duration: 168h  # 7 дней
  server:
    host: 0.0.0.0
    port: 50051

streaming_service:
  db:
    host: localhost
    port: 5432
    user: stream_user
    password: stream_password
    name: stream_db
    ssl_mode: disable
  server:
    host: 0.0.0.0
    port: 8080

chat_service:
  db:
    host: localhost
    port: 5432
    user: chat_user
    password: chat_password
    name: chat_db
    ssl_mode: disable
  server:
    host: 0.0.0.0
    port: 50052
  websocket:
    jwt_secret: super_secret_key
    rate_limit: 20 # сообщений в минуту
    write_timeout: 5 # секунд
  mongo:
    uri: "mongodb://localhost:27017"
    database: "chat_db"
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
