auth_service:
  db:
    host: localhost
    port: 5432
    user: auth_user
    password: auth_password
    name: auth_db
    ssl_mode: disable
  jwt:
    secret_key: super_secret_key
    access_token_duration: 15m
    refresh_token_duration: 168h  # 7 дней
  server:
    host: 0.0.0.0
    port: 50051