db:
  host: auth_db
  port: 5432
  user: auth_user
  password: auth_password
  name: auth_database
  ssl_mode: disable

jwt:
  secret_key: super_secret_key
  access_token_duration: 15m
  refresh_token_duration: 168h

grpc:
  host: 0.0.0.0
  port: 50051